export enum EventTypeEnum {
    HOUSE_PARTY = 'HOUSE_PARTY',
    BIRTHDAY_PARTY = 'BIRTHDAY_PARTY',
    BABY_SHOWER = 'BABY_SHOWER',
    WORK_PARTY = 'WORK_PARTY',
    OPENING_PARTY = 'OPENING_PARTY'
}